### ISSUE TITLE
openrazer razermug module does not exist

### ISSUE THREAD

**Issue by dim-geo** [vifino/vifino-overlay#28]
openrazer install fails because it expects a module that is no longer built.

```

  Building modules, stage 2.
  MODPOST 6 modules
  CC [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razeraccessory.mod.o
  LD [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razeraccessory.ko
  CC [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razercore.mod.o
  LD [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razercore.ko
  CC [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razerkbd.mod.o
  LD [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razerkbd.ko
  CC [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razerkraken.mod.o
  LD [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razerkraken.ko
  CC [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razermouse.mod.o
  LD [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razermouse.ko
  CC [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razermousemat.mod.o
  LD [M]  /var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver/razermousemat.ko
make[1]: Leaving directory '/usr/src/linux-5.4.8-xanmod'
make: Leaving directory '/var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999'
>>> Source compiled.
>>> Test phase [not enabled]: app-misc/openrazer-9999

>>> Install app-misc/openrazer-9999 into /var/tmp/portage/app-misc/openrazer-9999/image/
 * Installing razerkbd module
 * Installing razermouse module
 * Installing razermousemat module
 * Installing razerkraken module
 * Installing razermug module
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'razermug.ko'
 * ERROR: app-misc/openrazer-9999::vifino-overlay failed (install phase):
 *   doins failed
 * 
 * If you need support, post the output of `emerge --info '=app-misc/openrazer-9999::vifino-overlay'`,
 * the complete build log and the output of `emerge -pqv '=app-misc/openrazer-9999::vifino-overlay'`.
 * The complete build log is located at '/var/tmp/portage/app-misc/openrazer-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-misc/openrazer-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999/driver'
 * S: '/var/tmp/portage/app-misc/openrazer-9999/work/openrazer-9999'

>>> Failed to emerge app-misc/openrazer-9999, Log file:
```

Maybe ebuild must remove razermug line...

**Comment by Arnvidr** [comment]
There is a razeraccessory module, but no razermug module. Maybe this is a name-change? Changing the razermug line to razeraccessory allows openrazer to build and merge.

**Comment by vifino** [comment]
This issue was fixed by the OP a while ago, thanks!
