### ISSUE TITLE
Impossible to launch polychromatic-tray-applet and polychromatic-controller after last update

### ISSUE THREAD

**Issue by JulienDlq** [vifino/vifino-overlay#45]
Since the last update of ebuild, even after trying to emerge: dev-python/pylibacl, dev-python/pylibmc, I can not launch polychromatic-tray-applet and polychromatic-controller.

```
$ polychromatic-tray-applet -v
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 47, in <module>
    import pylib.preferences as pref
ModuleNotFoundError: No module named 'pylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 52, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'
```

```
$ polychromatic-controller
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 52, in <module>
    import pylib.preferences as pref
ModuleNotFoundError: No module named 'pylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 58, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'
```

**Comment by JulienDlq** [comment]
Nevermind, after a clean reinstall (without not needed dev-python/pylibacl, dev-python/pylibmc), everything works. :scream:
