### ISSUE TITLE
[SOLVED] cannot import name 'QtSvg'

### ISSUE THREAD

**Issue by dscharalampidis** [vifino/vifino-overlay#64]
Hello,

After successfully emerging, I am getting:
```
$ polychromatic-controller
Polychromatic's modules could not be imported.
Check all dependencies are installed, the Python environment variables are correct, or try re-installing the application.

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 70, in <module>
    raise e
  File "/usr/bin/polychromatic-controller", line 62, in <module>
    import polychromatic.controller as controller
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/__init__.py", line 1, in <module>
    from . import shared
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/shared.py", line 22, in <module>
    from PyQt5 import uic, QtSvg
ImportError: cannot import name 'QtSvg' from 'PyQt5' (/usr/lib/python3.9/site-packages/PyQt5/__init__.py)
```
Any assistance will be greatly appreciated.

**Comment by ppfeufer** [comment]
You probably need `dev-python/PyQt5` with the `svg` USE flag enabled.

**Comment by dscharalampidis** [comment]
@ppfeufer that was it!
Many thanks.

**Comment by vifino** [comment]
Thanks @ppfeufer, I've put it in the ebuild to ensure the svg USE is there.
